// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCIEDTyO0Oaquk1QxPBUfGntS9DxeL_Ec',
    appId: '1:41318422955:web:8223aa5f999f49cc1f9aee',
    messagingSenderId: '41318422955',
    projectId: 'first-fire-de55e',
    authDomain: 'first-fire-de55e.firebaseapp.com',
    storageBucket: 'first-fire-de55e.appspot.com',
    measurementId: 'G-BRXRGQ84TX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWJn9mnmTzHGaOtCJUkysFsyRRpOK0WWY',
    appId: '1:41318422955:android:7c480679214ec6f21f9aee',
    messagingSenderId: '41318422955',
    projectId: 'first-fire-de55e',
    storageBucket: 'first-fire-de55e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-BXmlqAQdWan8QGNaXOgDKSRN3RhbgU0',
    appId: '1:41318422955:ios:2d449de27a89679d1f9aee',
    messagingSenderId: '41318422955',
    projectId: 'first-fire-de55e',
    storageBucket: 'first-fire-de55e.appspot.com',
    iosClientId: '41318422955-s2koadck0d3j75gbt4pqoges2vn4ouvt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
